service: secrets-demo
image: ross-byrne/secrets-demo

# Deploy to these servers.
servers:
  web:
    - 178.104.105.5

proxy:
  ssl: true
  host: cheese.rossbyrne.dev
  app_port: 3000
  healthcheck:
    path: /api/health

registry:
  server: ghcr.io
  username:
    - KAMAL_REGISTRY_USERNAME
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64
  cache:
    type: gha

env:
  clear:
    MY_PUBLIC_CHEESE: Edam
  secret:
    - MY_SECRET_CHEESE

# Aliases are triggered with "bin/kamal <alias>". You can overwrite arguments on invocation:
# "bin/kamal app logs -r job" will tail logs from the first server in the job section.
aliases:
  apps: server exec docker exec kamal-proxy kamal-proxy list
  logs: app logs -f

# Configure rolling deploys by setting a wait time between batches of restarts.
boot:
  limit: 10 # Can also specify as a percentage of total hosts, such as "25%"
  wait: 2
